version: '3'
  
services:
  
  php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    environment: 
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  nginx:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8082:80
    volumes:
      - nginx_log:/var/log/nginx
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8086:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

volumes:
  mysql_data: {}
  nginx_log: {}